name: openchain-wallet
version: "0.6.2"
summary: Openchain Wallet is an open source distributed ledger technology.
description: >
   Openchain Server exposes a public HTTP API, which can be called by any program capable of making HTTP calls.
   To wrap all those operations in a user-friendly user interface, we also provide a client: the Openchain Wallet.
confinement: devmode

apps:
  openchain-wallet:
    command: bin/openchain-wallet

parts:
  nginx:
    plugin: make
    source: .
    stage-packages:
      - nginx

  www:
    plugin: dump
    source: .
    organize:
      openchain-wallet: usr/share/dotnet/openchain-wallet/
      openchain: bin/openchain-wallet
    after: [nginx]
